### PR TITLE
fix: play again not working in single player mode

### LINKED ISSUE #44: bug: play again not working in single player mode
Image

### PR DESCRIPTION
**Pull request by skanda-2003**
Closes #44

### CODE REVIEW

**Comment by skanda-2003** [comment]
The game state is still in GAME_OVER after the game ends, I have added a line so that the game state changes to INIT when a new game is started.

**Comment by skanda-2003** [comment]
Reverted the changes made earlier.

In the saga, when the startGame begins:

- If current state is GAME_OVER, it first changes to INIT and then to DISTRIBUTE_CARDS.

I added a if block to check whether the game state is in GAME_OVER, if yes then it is set to INIT. 
This block is only used for single player mode. 
This is not triggered for the series mode as at the end of a round, it is in GAME_SUMMARY state.

This change is required as if it goes directly, the screen is stuck in game over page.

File: src/store/sagas/gameFlowSaga.ts [hunk 1]
```diff
@@ -256,6 +256,13 @@ export default function* gameFlowSaga() {
 
   // Watch for game start
   yield takeEvery(startGame.type, function* (): Generator<any, void, any> {
+    // If we're at GAME_OVER (single-player end), route via INIT first
+    const currentStage: GameStage = yield select(selectStage);
+    if (currentStage === GameStages.GAME_OVER) {
+      yield put(gameStageTransition(GameStages.INIT));
+      // Yield a micro-delay to avoid takeLeading dropping the next transition
+      yield delay(0);
+    }
```
Comment (akash-suresh) [inline src/store/sagas/gameFlowSaga.ts]: Remove this piece of code. Let's make it similar to `GameRedux.handleNewSeries()`.
1. Call `dispatch(resetStateForNewSeries());` before `handleStartGame` inside `handleNewGame()` in GameRedux. This will reset game state & then call startGame
2. Rename `resetStateForNewSeries` to `resetStateForNewGame`.

**Comment by akash-suresh** [comment]
@skanda-2003 made changes for this. Merging it.
